import type { Metadata } from 'next';
import { Check, HeartHandshake, Scale, ShieldCheck } from 'lucide-react';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';

export const metadata: Metadata = { title: 'Про нас — Perfect Dim', description: 'Perfect Dim — агенція добірної заміської нерухомості біля Луцька.' };

export default function AboutPage() {
  return <main className="bg-[#f6f1e8]"><SiteHeader /><section className="pd-container grid gap-12 py-16 lg:grid-cols-2 lg:items-center lg:py-24"><div><p className="pd-eyebrow">Про Perfect Dim</p><h1 className="mt-5 text-5xl leading-[1.02] text-[#173326] sm:text-7xl">Добірна нерухомість. Людяний супровід.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5d6e63]">Ми створили Perfect Dim, щоб пошук заміського будинку був спокійним, зрозумілим і чесним. Працюємо з об’єктами поблизу Луцька та знаємо кожну локацію не лише за картою.</p></div><img src="/property-2.png" alt="Сучасний будинок у добірці Perfect Dim" className="aspect-[4/3] w-full object-cover" /></section>
    <section className="bg-[#173326] py-20 text-white"><div className="pd-container"><p className="pd-eyebrow">Наш підхід</p><div className="mt-10 grid gap-px bg-white/12 md:grid-cols-3">{[[HeartHandshake, 'Спочатку слухаємо', 'Уточнюємо сценарій життя, бюджет і справжні пріоритети родини.'], [ShieldCheck, 'Перевіряємо деталі', 'Документи, комунікації, стан будинку та реальна вартість — до рішення.'], [Scale, 'Захищаємо інтереси', 'Ведемо переговори й пояснюємо кожен крок угоди простою мовою.']].map(([Icon, title, copy]) => <div key={String(title)} className="bg-[#173326] p-8"><Icon className="size-7 text-[#c3a567]" /><h2 className="mt-8 text-3xl">{String(title)}</h2><p className="mt-4 text-sm leading-6 text-white/58">{String(copy)}</p></div>)}</div></div></section>
    <section className="pd-container grid gap-12 py-20 lg:grid-cols-[.7fr_1.3fr] lg:py-28"><div><p className="pd-eyebrow">Що отримуєте</p><h2 className="mt-4 text-4xl text-[#173326] sm:text-5xl">Одна команда на всьому шляху</h2></div><div className="grid gap-5 sm:grid-cols-2">{['Персональна добірка без інформаційного шуму', 'Організація переглядів у зручний день', 'Юридична перевірка будинку та ділянки', 'Переговори щодо ціни й умов', 'Координація нотаріуса та документів', 'Підтримка після передачі ключів'].map((item) => <p key={item} className="flex items-start gap-3 border-t border-[#173326]/12 pt-4 text-sm leading-6 text-[#52665a]"><Check className="mt-1 size-4 shrink-0 text-[#b99751]" /> {item}</p>)}</div></section><SiteFooter /></main>;
}
