import type { Metadata } from 'next';
import { Check, HeartHandshake, Scale, ShieldCheck } from 'lucide-react';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';

export const metadata: Metadata = { title: 'Про нас — Perfect Dim', description: 'Perfect Dim допомагає знайти, перевірити й купити будинок біля Луцька.' };

export default function AboutPage() {
  return <main className="bg-[#f6f1e8]"><SiteHeader /><section className="pd-container grid gap-12 py-16 lg:grid-cols-2 lg:items-center lg:py-24"><div><p className="pd-eyebrow">Агентство нерухомості</p><h1 className="mt-5 text-5xl leading-[1.02] text-[#173326] sm:text-7xl">Шукаємо та перевіряємо будинки біля Луцька</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5d6e63]">Працюємо з приватними будинками в Луцькому районі. До перегляду уточнюємо характеристики й стан об’єкта, а до завдатку перевіряємо документи на будинок і землю.</p></div><img src="/property-2.png" alt="Сучасний будинок у добірці Perfect Dim" className="aspect-[4/3] w-full object-cover" /></section>
    <section className="bg-[#173326] py-20 text-white"><div className="pd-container"><p className="pd-eyebrow">Що робимо</p><div className="mt-10 grid gap-px bg-white/12 md:grid-cols-3">{[[HeartHandshake, 'Фіксуємо критерії', 'Уточнюємо бюджет, площу, ділянку, стан ремонту та щоденні маршрути.'], [ShieldCheck, 'Перевіряємо будинок', 'Звіряємо документи, комунікації, технічний стан і заявлену вартість.'], [Scale, 'Готуємо угоду', 'Узгоджуємо ціну й умови, координуємо документи та роботу нотаріуса.']].map(([Icon, title, copy]) => <div key={String(title)} className="bg-[#173326] p-8"><Icon className="size-7 text-[#c3a567]" /><h2 className="mt-8 text-3xl">{String(title)}</h2><p className="mt-4 text-sm leading-6 text-white/58">{String(copy)}</p></div>)}</div></div></section>
    <section className="pd-container grid gap-12 py-20 lg:grid-cols-[.7fr_1.3fr] lg:py-28"><div><p className="pd-eyebrow">Етапи роботи</p><h2 className="mt-4 text-4xl text-[#173326] sm:text-5xl">Від заявки до передачі ключів</h2></div><div className="grid gap-5 sm:grid-cols-2">{['Добірка за бюджетом і параметрами', 'Організація переглядів у зручний день', 'Перевірка документів на будинок і землю', 'Переговори щодо ціни й умов', 'Координація нотаріуса та документів', 'Перевірка розрахунків і передача ключів'].map((item) => <p key={item} className="flex items-start gap-3 border-t border-[#173326]/12 pt-4 text-sm leading-6 text-[#52665a]"><Check className="mt-1 size-4 shrink-0 text-[#b99751]" /> {item}</p>)}</div></section><SiteFooter /></main>;
}
